---
services:
  portfolio:
    container_name: nextjs-portfolio
    image: nextjs-portfolio
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 128m
    networks:
      - frontend
    restart: unless-stopped
networks:
  frontend:
    external: true
