---
services:
  portfolio:
    container_name: nextjs-portfolio
    image: nextjs-portfolio
    mem_limit: 512m
    networks:
      - frontend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portfolio-http.rule=Host(`localhost:3000`)'
      - 'traefik.http.routers.portfolio-http.entrypoints=web'
      # - 'traefik.http.routers.portfolio-https.tls=true'
      # - 'traefik.http.routers.portfolio-https.tls.certresolver=cloudfare'
      # - 'traefik.http.routers.portfolio-https.entrypoints=websecure'
      # - 'traefik.http.routers.portfolio-https.rule=Host(`sourav.app`)'
    restart: unless-stopped
networks:
  frontend:
    external: true
